import {
  FaTachometerAlt,
  FaClipboardList,
  FaProjectDiagram,
  FaUsers,
  FaMoneyCheckAlt,
  FaUserSlash,
  FaUserCheck,
  FaComments,
  FaSignOutAlt,
  FaPlusSquare,
  FaBoxOpen,
  FaTags,
  FaMoneyBillWave,
  FaHeadset,
  FaUserCircle,
} from "react-icons/fa";

export const allNav = [
  // Admin Routes
  {
    id: 1,
    title: "Dashboard",
    icon: <FaTachometerAlt />,
    role: "admin",
    path: "/admin/dashboard",
  },
  {
    id: 2,
    title: "Orders",
    icon: <FaClipboardList />,
    role: "admin",
    path: "/admin/dashboard/orders",
  },
  {
    id: 3,
    title: "Category",
    icon: <FaProjectDiagram />,
    role: "admin",
    path: "/admin/dashboard/categories",
  },
  {
    id: 4,
    title: "Sellers",
    icon: <FaUsers />,
    role: "admin",
    path: "/admin/dashboard/sellers",
  },
  {
    id: 5,
    title: "Payment Request",
    icon: <FaMoneyCheckAlt />,
    role: "admin",
    path: "/admin/dashboard/payment-request",
  },
  {
    id: 6,
    title: "Deactive Sellers",
    icon: <FaUserSlash />,
    role: "admin",
    path: "/admin/dashboard/deactive-sellers",
  },
  {
    id: 7,
    title: "Seller Request",
    icon: <FaUserCheck />,
    role: "admin",
    path: "/admin/dashboard/seller-request",
  },
  {
    id: 8,
    title: "Live Chat",
    icon: <FaComments />,
    role: "admin",
    path: "/admin/dashboard/live-chat",
  },
  {
    id: 9,
    title: "Logout",
    icon: <FaSignOutAlt />,
    role: "admin",
    path: "/logout",
  },

  // Seller Routes
  {
    id: 10,
    title: "Dashboard",
    icon: <FaTachometerAlt />,
    role: "seller",
    path: "/seller/dashboard",
  },
  {
    id: 11,
    title: "Add Product",
    icon: <FaPlusSquare />,
    role: "seller",
    path: "/seller/dashboard/add-product",
  },
  {
    id: 12,
    title: "All Product",
    icon: <FaBoxOpen />,
    role: "seller",
    path: "/seller/dashboard/all-product",
  },
  {
    id: 13,
    title: "Discount Product",
    icon: <FaTags />,
    role: "seller",
    path: "/seller/dashboard/discount-product",
  },
  {
    id: 14,
    title: "Orders",
    icon: <FaClipboardList />,
    role: "seller",
    path: "/seller/dashboard/orders",
  },
  {
    id: 15,
    title: "Payments",
    icon: <FaMoneyBillWave />,
    role: "seller",
    path: "/seller/dashboard/payments",
  },
  {
    id: 16,
    title: "Chat Support",
    icon: <FaHeadset />,
    role: "seller",
    path: "/seller/dashboard/chat-support",
  },
  {
    id: 17,
    title: "Chat Customer",
    icon: <FaComments />,
    role: "seller",
    path: "/seller/dashboard/chat-customer",
  },
  {
    id: 18,
    title: "Profile",
    icon: <FaUserCircle />,
    role: "seller",
    path: "/seller/dashboard/profile",
  },
  {
    id: 19,
    title: "Logout",
    icon: <FaSignOutAlt />,
    role: "seller",
    path: "/seller/logout",
  },
];
